AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'backend

  Sample SAM Template for backend

  '
Parameters:
  BucketBackend:
    Type: String
  BucketLambda:
    Type: String
Globals:
  Function:
    Timeout: 60
    MemorySize: 512
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
Resources:
  PostGetSimilarTextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://${BucketLambda}/lambda.zip
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
      - S3ReadPolicy:
          BucketName:
            Ref: BucketBackend
      - S3ReadPolicy:
          BucketName:
            Ref: BucketLambda
      Events:
        PostText:
          Type: Api
          Properties:
            Path: /postText
            Method: post
Outputs:
  TextSimilarityApi:
    Description: API Gateway endpoint URL for Prod stage for GetSimilarText function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  PostGetSimilarTextFunctionArn:
    Description: GetSimilarText Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PostGetSimilarTextFunction
      - Arn
  PostGetSimilarTextLambdaIamRole:
    Description: Implicit IAM Role created for GetSimilarText function
    Value:
      Fn::GetAtt:
      - PostGetSimilarTextFunction
      - Arn
